# Generated by Django 4.2.7 on 2023-11-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('method_test', '0002_alter_postargs_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postargs',
            name='text',
            field=models.CharField(max_length=20, verbose_name='text'),
        ),
    ]
